<a href="https://colab.research.google.com/github/kuNalsharma0725/Machine_Learning_project/blob/main/Machine_Learning_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Load the dataset and a summary of its structure and quality.

In [ ]:
#Load the dataset
import numpy as np
import pandas as pd
df=pd.read_csv("/content/churnguard_data (1).csv")

In [ ]:
#Print first 5 values of the DataFrame
df.head()

,customerID,gender,SeniorCitizen,tenure,PhoneService,InternetService,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,CUST-0032,Male,0,21.0,YES,Fiber optic,Month-to-month,No,Credit card,29.73,600.01,Yes
1,CUST-0110,Male,0,55.0,YES,Fiber optic,Two year,Yes,Bank transfer,46.32,2515.48,No
2,CUST-0137,Female,1,46.0,Yes,Fiber optic,Month-to-month,No,Mailed check,87.06,4153.97,Yes
3,CUST-0089,Female,1,63.0,Yes,Fiber optic,Month-to-month,YES,Mailed check,56.97,3641.3,Yes
4,CUST-0919,Female,0,8.0,Yes,DSl,month to month,No,Electronic check,39.69,309.79,Yes

In [ ]:
#Shape of the Dataframe
df.shape

(1030, 12)

In [ ]:
#Columns names with datatypes
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1030 entries, 0 to 1029
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        1030 non-null   object
 1   gender            1030 non-null   object
 2   SeniorCitizen     1030 non-null   int64
 3   tenure            980 non-null    float64
 4   PhoneService      1030 non-null   object
 5   InternetService   1014 non-null   object
 6   Contract          1030 non-null   object
 7   PaperlessBilling  1030 non-null   object
 8   PaymentMethod     1030 non-null   object
 9   MonthlyCharges    955 non-null    float64
 10  TotalCharges      966 non-null    object
 11  Churn             1030 non-null   object
dtypes: float64(2), int64(1), object(9)
memory usage: 96.7+ KB

In [ ]:
#Count the missing values
df.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
tenure              50
PhoneService         0
InternetService     16
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges      75
TotalCharges        64
Churn                0
dtype: int64

In [ ]:
#Count the duplicates in the DataFrame
df.duplicated().sum()

np.int64(30)

In [ ]:
#Count the unique values of Churn column
df.value_counts("Churn")

Churn
No     598
Yes    278
NO      38
no      38
nO      27
YES     20
yEs     20
yes     11
Name: count, dtype: int64

In [ ]:
#Count the unique values of Contract column
df.value_counts("Contract")

Contract
Month-to-month    482
One year          192
Two year          163
month-to-month     43
month to month     42
Monthly            35
One Year           18
1 year             13
one year           12
2 year             11
Two Year           10
two year            9
Name: count, dtype: int64

#Clean the Dataset

In [ ]:
#Drop the customerID column
df = df.drop('customerID', axis=1)
df.head(3)

,gender,SeniorCitizen,tenure,PhoneService,InternetService,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Male,0,21.0,YES,Fiber optic,Month-to-month,No,Credit card,29.73,600.01,Yes
1,Male,0,55.0,YES,Fiber optic,Two year,Yes,Bank transfer,46.32,2515.48,No
2,Female,1,46.0,Yes,Fiber optic,Month-to-month,No,Mailed check,87.06,4153.97,Yes

In [ ]:
#Remove duplicate rows
df=df.drop_duplicates()
df.duplicated().sum()

np.int64(0)

In [ ]:
#Analyse the shape of data after removable of duplicates
df.shape

(1000, 11)

In [ ]:
#Number of different values in gender column
df.value_counts("gender")

gender
Male          452
Female        448
  Male         51
  Female       49
Name: count, dtype: int64

In [ ]:
#Number of different values in PaymentMethod Column
df.value_counts("PaymentMethod")

PaymentMethod
Electronic check        285
Credit card             207
Bank transfer           206
Mailed check            202
  Electronic check       36
  Mailed check           25
  Bank transfer          21
  Credit card            18
Name: count, dtype: int64

In [ ]:
#Strip whitespace from gender column
df["gender"] = df["gender"].str.strip()
df.value_counts('gender')

gender
Male      503
Female    497
Name: count, dtype: int64

In [ ]:
#Strip whitespace from PaymentMethod column
df["PaymentMethod"] = df["PaymentMethod"].str.strip()
df.value_counts('PaymentMethod')

PaymentMethod
Electronic check    321
Bank transfer       227
Mailed check        227
Credit card         225
Name: count, dtype: int64

In [ ]:
#Check number of different values in Churn column
df.value_counts('Churn')

Churn
No     582
Yes    270
NO      37
no      37
nO      26
YES     20
yEs     18
yes     10
Name: count, dtype: int64

In [ ]:
#Strip whitespace from Churn column
df["Churn"] = df["Churn"].str.strip().str.title()
df.value_counts('Churn')

Churn
No     682
Yes    318
Name: count, dtype: int64

In [ ]:
#Check number of different value in Phoneservice column
df.value_counts('PhoneService')

PhoneService
Yes    758
No      83
YES     51
yEs     49
yes     46
no       7
nO       4
NO       2
Name: count, dtype: int64

In [ ]:
#Strip whitespace from PhoneService column
df["PhoneService"] = df["PhoneService"].str.strip().str.title()
df.value_counts('PhoneService')

PhoneService
Yes    904
No      96
Name: count, dtype: int64

In [ ]:
#Check number of different values in PaperlessBilling column
df.value_counts('PaperlessBilling')

PaperlessBilling
Yes    509
No     339
no      29
yes     28
YES     26
NO      25
yEs     23
nO      21
Name: count, dtype: int64

In [ ]:
#Strip whitespace from PaperlessBilling column
df["PaperlessBilling"] = df["PaperlessBilling"].str.strip().str.title()
df.value_counts('PaperlessBilling')

PaperlessBilling
Yes    586
No     414
Name: count, dtype: int64

In [ ]:
#Check number of different values in Contract column
df.value_counts('Contract')

Contract
Month-to-month    466
One year          187
Two year          158
month-to-month     42
month to month     41
Monthly            35
One Year           17
1 year             13
one year           12
2 year             11
Two Year            9
two year            9
Name: count, dtype: int64

In [ ]:
# Define mapping dictionary
contract_mapping = {
    'month-to-month': 'Month-to-month',
    'monthly': 'Month-to-month',
    'one year': 'One year',
    '1 year': 'One year',
    'two year': 'Two year',
    '2year': 'Two year'
}

# Clean and map
df['Contract'] = (
    df['Contract']
    .str.strip()       # Remove leading/trailing spaces
    .str.lower()       # Convert to lowercase to catch 'Two Year', 'two year', etc.
    .map(contract_mapping) # Map to valid values
)

In [ ]:
df.value_counts('Contract')

Contract
Month-to-month    543
One year          229
Two year          176
Name: count, dtype: int64

In [ ]:
#Check number of different values in Contract column
df.value_counts('InternetService')

InternetService
Fiber optic    336
DSL            317
No             185
Fibre optic     31
fiber optic     24
dsl             21
DSl             19
FiberOptic      17
Dsl             15
NO              13
no               6
Name: count, dtype: int64

In [ ]:
# Define mapping dictionary
contract_mapping = {
    'Fibre optic': 'Fiber optic',
    'fiber optic': 'Fiber optic',
    'FiberOptic': 'Fiber optic',
    'dsl': 'DSL',
    'DSl': 'DSL',
    'Dsl': 'DSL',
    'no': 'No',
    'NO': 'No'
}

# Clean and map
df['InternetService'] = (
    df['InternetService']
    .str.strip()       # Remove leading/trailing spaces
    .str.lower()       # Convert to lowercase
    .map(contract_mapping) # Map to valid values
)
df.value_counts('InternetService')

InternetService
DSL            372
Fiber optic    360
No             204
Name: count, dtype: int64

In [ ]:
#Check number of different values in TotalCharges column
df.value_counts('TotalCharges')

TotalCharges
--         16
na          8
?           6
            4
3916.82     2
           ..
2314.66     1
2316.38     1
2317.48     1
2317.54     1
225.3       1
Name: count, Length: 902, dtype: int64

In [ ]:
#Fix TotalCharges
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
#Fill NaN values with median
df['TotalCharges'] = df['TotalCharges'].fillna(df['TotalCharges'].median())
df['TotalCharges'].dtype

dtype('float64')

In [ ]:
#Remove rows where tenure is zero or negative
df = df[df['tenure'] > 0]

In [ ]:
#Remove rows where MonthlyCharges is less than 10 or greater than 200
df = df[(df['MonthlyCharges'] >= 10) & (df['MonthlyCharges'] <= 200)]

In [ ]:
df.isna().sum()

gender               0
SeniorCitizen        0
tenure               0
PhoneService         0
InternetService     58
Contract            45
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges         0
Churn                0
dtype: int64

In [ ]:
#Fill null values
df['InternetService'] = df['InternetService'].fillna('Unknown')
df['Contract'] = df['Contract'].fillna('Unknown')

In [ ]:
#Check Null values
df.isna().sum()

gender              0
SeniorCitizen       0
tenure              0
PhoneService        0
InternetService     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [ ]:
df.shape

(867, 11)

#Train a Classification Model

In [ ]:
#Encode Churn column
df['Churn'] = df['Churn'].map({'Yes': 1, 'No': 0})
df['Churn'].head()

0    1
1    0
2    1
3    1
4    1
Name: Churn, dtype: int64

In [ ]:
#Encode categorical columns
df = pd.get_dummies(df, columns=['gender', 'PhoneService', 'InternetService', 'Contract', 'PaperlessBilling', 'PaymentMethod'
], drop_first=True)

In [ ]:
df.head()

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,Churn,gender_Male,PhoneService_Yes,InternetService_Fiber optic,InternetService_No,InternetService_Unknown,Contract_One year,Contract_Two year,Contract_Unknown,PaperlessBilling_Yes,PaymentMethod_Credit card,PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,21.0,29.73,600.01,1,True,True,True,False,False,False,False,False,False,True,False,False
1,0,55.0,46.32,2515.48,0,True,True,True,False,False,False,True,False,True,False,False,False
2,1,46.0,87.06,4153.97,1,False,True,True,False,False,False,False,False,False,False,False,True
3,1,63.0,56.97,3641.30,1,False,True,True,False,False,False,False,False,True,False,False,True
4,0,8.0,39.69,309.79,1,False,True,False,False,False,False,False,True,False,False,True,False

In [ ]:
df.shape

(867, 17)

In [ ]:
#Separate the data into features and label
y = df["Churn"]
X = df.drop(columns=["Churn"])
print(X.shape)
y.shape

(867, 16)

(867,)

In [ ]:
#Split into train and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(693, 16)
(174, 16)
(693,)
(174,)

In [ ]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
#Train the model
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train_scaled, y_train)

LogisticRegression()

In [ ]:
#MODEL EVALUATION
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_auc_score
y_pred = model.predict(X_test_scaled)
y_prob = model.predict_proba(X_test_scaled)[:, 1] # Probability of class 1

print("---  Evaluation Metrics ---")
print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")
print(f"ROC-AUC Score: {roc_auc_score(y_test, y_prob):.4f}\n")

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred), "\n")

print("Classification Report:")
print(classification_report(y_test, y_pred))

---  Evaluation Metrics ---
Accuracy: 0.7069
ROC-AUC Score: 0.7011

Confusion Matrix:
[[103  19]
 [ 32  20]]

Classification Report:
              precision    recall  f1-score   support

           0       0.76      0.84      0.80       122
           1       0.51      0.38      0.44        52

    accuracy                           0.71       174
   macro avg       0.64      0.61      0.62       174
weighted avg       0.69      0.71      0.69       174

In [ ]:
# Generate classification report with custom class labels
report = classification_report(
    y_test, y_pred, target_names=["Stay", "Churn"]
)

print(report)

              precision    recall  f1-score   support

        Stay       0.76      0.84      0.80       122
       Churn       0.51      0.38      0.44        52

    accuracy                           0.71       174
   macro avg       0.64      0.61      0.62       174
weighted avg       0.69      0.71      0.69       174

#Build a Prediction Script

In [ ]:
#Collect Inputs from User
tenure = int(input("Enter tenure (months): "))
monthly_charges = float(input("Enter Monthly Charges: "))
total_charges = float(input("Enter Total Charges: "))
senior_citizen = int(input("Senior Citizen? (1 = Yes, 0 = No): "))
contract = int(input("Contract type (0 = Month-to-month, 1 = One year, 2 = Two year): "))

Enter tenure (months): 24
Enter Monthly Charges: 65.50
Enter Total Charges: 1500
Senior Citizen? (1 = Yes, 0 = No): 0
Contract type (0 = Month-to-month, 1 = One year, 2 = Two year): 1

In [ ]:
import pandas as pd
import numpy as np

# Make Prediction
# Create a dictionary initialized to 0 / False matching training feature names
input_dict = {col: [0] for col in X_train.columns}

# Map numerical inputs directly
input_dict['tenure'] = [tenure]
input_dict['MonthlyCharges'] = [monthly_charges]
input_dict['TotalCharges'] = [total_charges]
input_dict['SeniorCitizen'] = [senior_citizen]

# Map categorical values based on user inputs from the previous step
if contract == 1:
    input_dict['Contract_One year'] = [True]
elif contract == 2:
    input_dict['Contract_Two year'] = [True]

# Construct the DataFrame matching X_train column ordering exactly
user_data = pd.DataFrame(input_dict)[X_train.columns]

# Scale the user data using the same scaler used during training
user_data_scaled = scaler.transform(user_data)

In [ ]:
# Predict
prediction = model.predict(user_data_scaled)[0]
result = "Churn" if prediction == 1 else "Stay"
print(f"Prediction: The customer is likely to {result}")

Prediction: The customer is likely to Stay